rust: fix test by adding `rustc` to `PATH`
The specific error that I was seeing:
```shell-session
$ /usr/local/Cellar/rust/1.18.0_1/bin/cargo run --verbose
error: could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
```