sproxy: fix permissions error in `make install`
- instead of using `share.install prefix+"man"`, tweak the Makefile
  directly so that it honors $(mandir)

- fix sandbox violation by passing `PREFIX=$(prefix)` to `Makefile.PL`s
    ERROR: Can't create '/usr/local/share/man/man3'
    Do not have write permissions on '/usr/local/share/man/man3'
    Sandbox: perl5.18(39244) deny(1) file-write-create /usr/local/share/man/man3

- add a test