remove mirror as the file is no longer present
```
==> Installing openconnect dependency: oath-toolkit
==> Downloading https://download.savannah.gnu.org/releases/oath-toolkit/oath-toolkit-2.6.1.tar.gz
==> Downloading from http://mirrors.cicku.me/savannah//oath-toolkit/oath-toolkit-2.6.1.tar.gz
HTTPS to HTTP redirect detected & HOMEBREW_NO_INSECURE_REDIRECT is set.
Trying a mirror...
==> Downloading https://fossies.org/linux/privat/oath-toolkit-2.6.1.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "oath-toolkit"
Download failed: https://fossies.org/linux/privat/oath-toolkit-2.6.1.tar.gz
```