opencv: fix Yosemite build by disabling AVX2
OpenCV adds runtime support for the AVX2
instruction set (amongst others) to accelerate some
algorithms on CPUs that support these instructions.
However, the compiler in Mac OS 10.10 (Yosemite) or
older does not fully support AVX2, so the build fails
with errors such as
"error: use of undeclared identifier '_mm256_cvtps_ph'"
Work around this by disabling AVX2 on older Mac OS.